{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.hadat.datsdk",
    "module": "sdk-ads",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.hadat.datsdk",
          "module": "sdk-core",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.android.libraries.ads.mobile.sdk",
          "module": "ads-mobile-sdk",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ads-0.1.0.aar",
          "url": "sdk-ads-0.1.0.aar",
          "size": 328739,
          "sha512": "92f47928f17aaab8560ebca2629aad4e178754544a6e019f82a9837477aef856177cbe1e8e4e19a780189e686d9ba56625fd5acb7f34a79e8cf9ac5d5a533487",
          "sha256": "a355797764424a5b784087c41e04915e9d90c82c37edd7f2e6c7f2e959f86131",
          "sha1": "8fd363377aadde645f8c0c8596b49c4f851d8838",
          "md5": "73f947e9a6bd3a33583bff34b5ae5f5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.faltenreich",
          "module": "skeletonlayout",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.ads.mediation",
          "module": "pangle",
          "version": {
            "requires": "8.3.0.3.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "34.13.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "dev.hadat.datsdk",
          "module": "sdk-core",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "com.google.android.libraries.ads.mobile.sdk",
          "module": "ads-mobile-sdk",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads"
            },
            {
              "group": "com.google.android.gms",
              "module": "play-services-ads-lite"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ads-0.1.0.aar",
          "url": "sdk-ads-0.1.0.aar",
          "size": 328739,
          "sha512": "92f47928f17aaab8560ebca2629aad4e178754544a6e019f82a9837477aef856177cbe1e8e4e19a780189e686d9ba56625fd5acb7f34a79e8cf9ac5d5a533487",
          "sha256": "a355797764424a5b784087c41e04915e9d90c82c37edd7f2e6c7f2e959f86131",
          "sha1": "8fd363377aadde645f8c0c8596b49c4f851d8838",
          "md5": "73f947e9a6bd3a33583bff34b5ae5f5f"
        }
      ]
    }
  ]
}
