{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.hadat.datsdk",
    "module": "sdk-billing",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.hadat.datsdk",
          "module": "sdk-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-billing-0.3.0.aar",
          "url": "sdk-billing-0.3.0.aar",
          "size": 83607,
          "sha512": "a697eb49b853c035bc3dbb664654a4af359bf9adf87faf0ebaad6eaabc361c112241a0220fee29c5eb2019b0d356d24a6f3752fc6affc1d7ee55440de6d5dd84",
          "sha256": "84b0a01661516452d07a0a1e7b7c38270b4a49dcbe3bd1e3d544169df1f95219",
          "sha1": "967a9dc83a40f5ca453d6a0f8181b933ab734680",
          "md5": "340d42c19e56085508590e7f4b18809d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "dev.hadat.datsdk",
          "module": "sdk-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-billing-0.3.0.aar",
          "url": "sdk-billing-0.3.0.aar",
          "size": 83607,
          "sha512": "a697eb49b853c035bc3dbb664654a4af359bf9adf87faf0ebaad6eaabc361c112241a0220fee29c5eb2019b0d356d24a6f3752fc6affc1d7ee55440de6d5dd84",
          "sha256": "84b0a01661516452d07a0a1e7b7c38270b4a49dcbe3bd1e3d544169df1f95219",
          "sha1": "967a9dc83a40f5ca453d6a0f8181b933ab734680",
          "md5": "340d42c19e56085508590e7f4b18809d"
        }
      ]
    }
  ]
}
