{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.hadat.datsdk",
    "module": "sdk-core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.chibatching.kotpref",
          "module": "kotpref",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "initializer",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-0.2.0.aar",
          "url": "sdk-core-0.2.0.aar",
          "size": 6865,
          "sha512": "19f09845a0013f10e556e371e1380c723613afd3c3a9a890da764e369724dd18f8393c80be8889b2b7e1dedf8ad19c2c437559ae8320ed32cdc64870a7c182c6",
          "sha256": "dfc5647fc33ab5fccd9b6195e34a7771110dd2fedb22e114c10dc991ea23446c",
          "sha1": "7882e3d3e853fd9bd5bb8c0a4fa8afb38c45dae4",
          "md5": "0959bbea7f8e640fd42cad2d318d9a67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "kotpref",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "initializer",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-0.2.0.aar",
          "url": "sdk-core-0.2.0.aar",
          "size": 6865,
          "sha512": "19f09845a0013f10e556e371e1380c723613afd3c3a9a890da764e369724dd18f8393c80be8889b2b7e1dedf8ad19c2c437559ae8320ed32cdc64870a7c182c6",
          "sha256": "dfc5647fc33ab5fccd9b6195e34a7771110dd2fedb22e114c10dc991ea23446c",
          "sha1": "7882e3d3e853fd9bd5bb8c0a4fa8afb38c45dae4",
          "md5": "0959bbea7f8e640fd42cad2d318d9a67"
        }
      ]
    }
  ]
}
