{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.hadat.datsdk",
    "module": "sdk-core",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.chibatching.kotpref",
          "module": "kotpref",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "initializer",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-0.2.0.aar",
          "url": "sdk-core-0.2.0.aar",
          "size": 6868,
          "sha512": "2192d817ff922f45afe4151c52f3c21f8e4fb8724868fb87a2ae02859a86c6c8dcebe38d8e47509d0635f0fcb2a0a8835808c2be19486a3a5cbb65978bf321df",
          "sha256": "b436dc42daf27ec785dec0ce31583030a72973c0c1ddf98d7a4c4cc7a4c07d29",
          "sha1": "20fd3c5ff1296fe68497de1bd6bacadb8fb7b89c",
          "md5": "3f43cc7dc5410342a00321e459d8aa7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "kotpref",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.chibatching.kotpref",
          "module": "initializer",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-0.2.0.aar",
          "url": "sdk-core-0.2.0.aar",
          "size": 6868,
          "sha512": "2192d817ff922f45afe4151c52f3c21f8e4fb8724868fb87a2ae02859a86c6c8dcebe38d8e47509d0635f0fcb2a0a8835808c2be19486a3a5cbb65978bf321df",
          "sha256": "b436dc42daf27ec785dec0ce31583030a72973c0c1ddf98d7a4c4cc7a4c07d29",
          "sha1": "20fd3c5ff1296fe68497de1bd6bacadb8fb7b89c",
          "md5": "3f43cc7dc5410342a00321e459d8aa7b"
        }
      ]
    }
  ]
}
